title: The Walt Whitman Journal of Psychology
url: wwjop.org
excerpt_separator: <!-- end excerpt -->
source: src
exclude:
  - README.md
  - .gitignore
  - run.sh
  - CNAME
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-minifier
defaults:
  -
    scope:
      path: ""
    values:
      layout: "short-navbar"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext