title: The Whitman Journal of Psychology
url: whitmanpsychjournal.org
excerpt_separator: <!-- end excerpt -->
source: src
destination: src/_site
exclude:
  - README.md
  - .gitignore
  - run.sh
  - CNAME
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"