title: The Walt Whitman Journal of Psychology
url: wwjop.org
description: >- 
  The Walt Whitman Journal of Psychology is the only High School Psychology journal
  in the United States. Made by students, for students, the Journal enables access
  of student research to teachers and students worldwide.

excerpt_separator: <!-- end excerpt -->

# source: src
exclude:
  - README.md
  - .gitignore
  - run.sh
  - CNAME
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-minifier
defaults:
  -
    scope:
      path: ""
    values:
      layout: "short-navbar"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext